In [10]:
import numpy as np
import statsmodels.api as sm

In [11]:
data = sm.datasets.longley.load()

In [12]:
data

<class 'statsmodels.datasets.utils.Dataset'>

In [13]:
data.exog = sm.add_constant(data.exog)

In [14]:
data.exog

const  GNPDEFL       GNP   UNEMP   ARMED       POP    YEAR
0     1.0     83.0  234289.0  2356.0  1590.0  107608.0  1947.0
1     1.0     88.5  259426.0  2325.0  1456.0  108632.0  1948.0
2     1.0     88.2  258054.0  3682.0  1616.0  109773.0  1949.0
3     1.0     89.5  284599.0  3351.0  1650.0  110929.0  1950.0
4     1.0     96.2  328975.0  2099.0  3099.0  112075.0  1951.0
5     1.0     98.1  346999.0  1932.0  3594.0  113270.0  1952.0
6     1.0     99.0  365385.0  1870.0  3547.0  115094.0  1953.0
7     1.0    100.0  363112.0  3578.0  3350.0  116219.0  1954.0
8     1.0    101.2  397469.0  2904.0  3048.0  117388.0  1955.0
9     1.0    104.6  419180.0  2822.0  2857.0  118734.0  1956.0
10    1.0    108.4  442769.0  2936.0  2798.0  120445.0  1957.0
11    1.0    110.8  444546.0  4681.0  2637.0  121950.0  1958.0
12    1.0    112.6  482704.0  3813.0  2552.0  123366.0  1959.0
13    1.0    114.2  502601.0  3931.0  2514.0  125368.0  1960.0
14    1.0    115.7  518173.0  4806.0  2572.0  127852.0  1961.0
15    1.0    116.9  554894.0  4007.0  2827.0  130081.0  1962.0

In [15]:
results = sm.OLS(data.endog, data.exog).fit()

In [16]:
results

In [17]:
A = np.identity(len(results.params))

In [18]:
A

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [19]:
A = A[1:,:]

In [20]:
A

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
print(results.f_test(A))

<F test: F=330.2853392856962, p=4.984030525275679e-10, df_denom=9, df_num=6>


In [22]:
results.fvalue

330.28533923420713

In [23]:
results.f_pvalue

4.984030528750515e-10

In [24]:
B = np.array(([0,0,1,-1,0,0,0],[0,0,0,0,0,1,-1]))

In [25]:
B

array([[ 0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1, -1]])

In [26]:
print(results.f_test(B))

<F test: F=9.740461873302612, p=0.005605288531739092, df_denom=9, df_num=2>
